.TH "shjpegshow" 1 "Nov 2009" "SH JPEG" "Linux-SH Multimedia"

.SH NAME
shjpegshow \- Photo Frame app for MS7724SE

.SH SYNOPSIS

.B \fBshjpegshow\fR \fI[OPTIONS]\fR \fI<directory>\fR

.SH DESCRPITOIN
.B shjpegshow
Decodeds JPEG files in given directory. See \fB--help\fR for more details.

.SH AUTHORS
shjpegshow was written by Takanari Hayama

Please report bugs to <taki@igel.co.jp>
