.TH "shjpegtest" 1 "Nov 2009" "SH JPEG" "Linux-SH Multimedia"

.SH NAME
shjpegshow \- Encode/decode JPEG images using the SH-Mobile JPU

.SH SYNOPSIS

.B \fBshjpegtest\fR \fI[OPTIONS]\fR \fI<jpegfile>\fR \fI[<output>]\fR

.SH DESCRPITOIN
.B shjpegtest
Decodeds given JPEG file, and then re-encode. See \fB--help\fR for more details.

.SH AUTHORS
shjpegtest was written by Takanari Hayama

Please report bugs to <taki@igel.co.jp>
